# Generated by Django 5.2.8 on 2025-11-19 18:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Гос. номер')),
                ('fuel_consumption_rate', models.FloatField(verbose_name='Норма расхода (л/100км)')),
                ('inspection_due_date', models.DateField(verbose_name='Дата окончания техосмотра')),
                ('insurance_due_date', models.DateField(verbose_name='Дата окончания страховки')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('contact_info', models.CharField(max_length=200, verbose_name='Контактные данные')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='TravelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_number', models.CharField(max_length=50, verbose_name='Номер путевого листа')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата поездки')),
                ('departure_time', models.TimeField(verbose_name='Время выезда')),
                ('return_time', models.TimeField(verbose_name='Время возвращения')),
                ('start_mileage', models.FloatField(verbose_name='Показания спидометра при выезде')),
                ('end_mileage', models.FloatField(verbose_name='Показания спидометра при возвращении')),
                ('route', models.TextField(verbose_name='Маршрут следования')),
                ('fuel_balance_start', models.FloatField(verbose_name='Остаток горючего при выезде')),
                ('fuel_issued', models.FloatField(default=0, verbose_name='Выдано горючего')),
                ('fuel_balance_end', models.FloatField(verbose_name='Остаток горючего при возвращении')),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.automobile', verbose_name='Автомобиль')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Путевой лист',
                'verbose_name_plural': 'Путевые листы',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
