# Generated by Django 5.2.8 on 2025-11-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее изменение'),
        ),
    ]
