# Generated by Django 5.2.8 on 2025-11-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_automobile_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='full_name',
        ),
        migrations.AddField(
            model_name='driver',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='driver',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
    ]
