# Generated by Django 5.2.8 on 2025-11-20 13:40

import django.utils.timezone
import fleet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_remove_driver_full_name_driver_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travellog',
            options={'ordering': ['-start_date', '-id'], 'verbose_name': 'Путевой лист', 'verbose_name_plural': 'Путевые листы'},
        ),
        migrations.RemoveField(
            model_name='travellog',
            name='date',
        ),
        migrations.AddField(
            model_name='automobile',
            name='current_mileage',
            field=models.FloatField(default=0, verbose_name='Текущий пробег (км)'),
        ),
        migrations.AddField(
            model_name='travellog',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания поездки'),
        ),
        migrations.AddField(
            model_name='travellog',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала поездки'),
        ),
        migrations.AlterField(
            model_name='travellog',
            name='log_number',
            field=models.CharField(default=fleet.models.get_next_log_number, max_length=50, verbose_name='Номер путевого листа'),
        ),
    ]
